version: "3.8"

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env # .env 파일 로드
    volumes:
      - .:/app
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - flask-app
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my_network

networks:
  my_network: