version: "3.8"

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env # .env 파일 로드
    volumes:
      - .:/app
    networks:
      - my_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - flask-app
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network: