# version: "3.8"

services:
  flask-app:
    build: .
    container_name: flask_app
    ports:
      - "8000:8000" # Nginx가 접근할 수 있도록 포트 노출
    depends_on:
      - db    
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=mysql+pymysql://root:1234@localhost/users
    volumes:
      - .:/app  # 개발 시 코드 반영 가능
  
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: users
      MYSQL_USER: root 
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - flask-app
    ports:
      - "80:80"  # 외부에서 80번 포트 접근 가능
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Nginx 설정 파일 적용

volumes:
  mysql_data: